### ISSUE TITLE
Logo centering not working as intended

### ISSUE THREAD

**Issue by kylebuildsstuff** [Shopify/checkout-branding#3]
Centering a logo using the branding logo alignment setting doesn't seem to work properly.

The breadcrumbs center as expected but the logo does not. This recently came to my attention from a merchant but I'm not sure if there's anything I can do about it.

Here's what it looks like when alignment is set to the left:

<img width="734" alt="left" src="https://user-images.githubusercontent.com/17548405/196032523-f0b5ea41-5289-4111-800f-6eec24340900.png">

Here's what it looks like when alignment is set to centered:

<img width="877" alt="center" src="https://user-images.githubusercontent.com/17548405/196032528-7c9cbb57-9b06-443a-a0b6-9ca0f193d86b.png">

What was expected was that the logo would be centered too.

**Comment by jun-shop** [comment]
fairly sure this is not an issue currently as i cannot repro this, but feel free to reopen if you think it is still happening.
